# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'macos-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn test
    displayName: 'Yarn install & build'

  - task: Gradle@2
    inputs:
      workingDirectory: './android'
      gradleWrapperFile: './android/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'app:assembleRelease'
