const OPEN_ARTICLE_START = 'OPEN_ARTICLE_START'
const FETCH_FROM_CACHE_START = 'FETCH_FROM_CACHE_START'
const FETCH_FROM_CACHE_END = 'FETCH_FROM_CACHE_END'
const REFRESH_CACHE_START = 'REFRESH_CACHE_START'
const REFRESH_CACHE_END = 'REFRESH_CACHE_END'

export default {
	OPEN_ARTICLE_START,
	FETCH_FROM_CACHE_START,
	FETCH_FROM_CACHE_END,
	REFRESH_CACHE_START,
	REFRESH_CACHE_END
}
