# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nepaltodayapp' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nepaltodayapp

  

  platform :ios, '9.0'




  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'

  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'nepaltodayappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'nepaltodayapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nepaltodayapp-tvOS

  target 'nepaltodayapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
